# Week 2 – NumPy & Pandas Homework  
**Name:** Reem Aboutaleb  

This notebook includes my solutions for both NumPy and Pandas practice questions.


Part A — NumPy

In [ ]:
import numpy as np


In [ ]:
# 1️⃣ Define two custom numpy arrays (A, B) and stack vertically & horizontally
A = np.array([[1, 5, 9],
              [4, 7, 10]])

B = np.array([[2, 5, 8],
              [3, 6, 9]])

v_stack = np.vstack((A, B))   # vertical stack (A over B)
h_stack = np.hstack((A, B))   # horizontal stack (A beside B)

print("A:\n", A)
print("\nB:\n", B)
print("\nVertical Stack:\n", v_stack)
print("\nHorizontal Stack:\n", h_stack)



A:
 [[ 1  5  9]
 [ 4  7 10]]

B:
 [[2 5 8]
 [3 6 9]]

Vertical Stack:
 [[ 1  5  9]
 [ 4  7 10]
 [ 2  5  8]
 [ 3  6  9]]

Horizontal Stack:
 [[ 1  5  9  2  5  8]
 [ 4  7 10  3  6  9]]


In [ ]:
# 2️⃣ Find common elements between A and B (Intersection)
common = np.intersect1d(A, B)
print("Common elements:", common)



Common elements: [5 9]


In [ ]:
# 3️⃣ Extract numbers from A between 5 and 10
mask = (A >= 5) & (A <= 10)
vals_mask = A[mask]
print("Values in [5,10] (boolean mask):", vals_mask)

# Using np.where()
idx = np.where((A >= 5) & (A <= 10))
print("Indices from np.where:", idx)
print("Values from np.where:", A[idx])



Values in [5,10] (boolean mask): [ 5  9  7 10]
Indices from np.where: (array([0, 0, 1, 1]), array([1, 2, 1, 2]))
Values from np.where: [ 5  9  7 10]


In [ ]:
# 4️⃣ Filter iris_2d rows where petallength > 1.5 and sepallength < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("First 5 filtered rows:\n", filtered_rows[:5])
print("Total rows matching:", filtered_rows.shape[0])



First 5 filtered rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]
Total rows matching: 6


Part B — Pandas

In [ ]:
import pandas as pd
import numpy as np




In [ ]:
# 1️⃣ Filter 'Manufacturer', 'Model', 'Type' for every 20th row (starting at 0)
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

every_20th = df.iloc[::20, :]
result_cols = every_20th[['Manufacturer', 'Model', 'Type']]

print("Every 20th row (selected columns):\n")
print(result_cols)




Every 20th row (selected columns):

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [ ]:
# 2️⃣ Replace missing values in Min.Price and Max.Price with their means (no chained-assignment warning)
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Explicit assignment (future-proof)
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print("NaN values replaced with column means.\n")
print(df[['Min.Price', 'Max.Price']].head())
print("\nMissing values remaining:\n", df[['Min.Price', 'Max.Price']].isna().sum())





NaN values replaced with column means.

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

Missing values remaining:
 Min.Price    0
Max.Price    0
dtype: int64


In [ ]:
# 3️⃣ Get rows where row sum > 100 (reproducible)
np.random.seed(42)

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4),
                  columns=['A','B','C','D'])

rows_gt_100 = df[df.sum(axis=1) > 100]
print("Rows where sum > 100:\n", rows_gt_100)



Rows where sum > 100:
      A   B   C   D
0   16  29  38  24
1   20  17  38  30
2   16  35  28  32
3   20  20  33  30
5   31  30  11  33
8   35  31  38  21
9   34  26  36  36
10  19  37  37  25
11  24  39  39  24
12  39  28  21  32


# Thank You  
This notebook was completed by **Reem Aboutaleb** for Week 2 Homework (NumPy & Pandas).  
Thank you for reviewing my work!
